## =====================================================================
##  liveFallback.R
##  Shared helper for making live-API-dependent tests/vignette chunks
##  resilient to a source being transiently unreachable, without losing
##  test coverage (skip_if_offline_dti()-style skipping) or crashing a
##  vignette render (which Bioconductor's nightly build also executes
##  live, so an upstream outage there fails the official build, not just
##  a local preview).
##
##  Pattern: try the live call; on ANY error, substitute a pregenerated
##  result shipped in inst/extdata/fixtures/ instead of propagating the
##  error. This generalizes a pattern that already existed for exactly
##  one Rd example (man/runDrugTarget_Annot_Bioassay.Rd's \donttest{}/
##  \dontshow{} pair, substituting inst/extdata/paralogs2_res_list.rds).
##
##  Fixtures are regenerated by inst/scripts/generate_live_fixtures.R -
##  see that script's header for when to rerun it.
## =====================================================================

#' Try a live call; on failure, substitute a shipped cached result
#'
#' \code{expr} is evaluated lazily (ordinary R promise semantics), so the
#' live call happens exactly once, inside the \code{tryCatch()} - nothing
#' is evaluated twice. On success, the live result is returned unchanged
#' (no fixture is read). On any error, a message is emitted, the fixture
#' at \code{inst/extdata/fixtures/<fixture>} is loaded (a list with
#' elements \code{result} and \code{cachedDate}, written by
#' \code{inst/scripts/generate_live_fixtures.R}), and returned with
#' \code{attr(, "dtiCached") <- TRUE} / \code{attr(, "dtiCachedDate")}
#' set so callers can tell which path was taken.
#'
#' Call-site rule: check \code{attr(result, "dtiCached")} (and emit any
#' visible "showing cached results" note) immediately after calling this
#' - subsetting a data.frame (\code{df[, cols]}) drops custom attributes,
#' so the check must happen before any further transformation.
#'
#' @keywords internal
#' @noRd
.dtiLiveOrCached <- function(expr, fixture, label) {
    useCached <- function(reason) {
        message("live call to '", label, "' failed (", reason,
                "); using shipped cached result instead")
        path <- system.file("extdata", "fixtures", fixture,
                            package = "drugTargetInteractions")
        cached <- readRDS(path)
        out <- cached$result
        attr(out, "dtiCached") <- TRUE
        attr(out, "dtiCachedDate") <- cached$cachedDate
        out
    }
    ## Two failure shapes, both of which must fall back. An error covers
    ## callers that stop outright (biomaRt's getParalogs()). A
    ## `dtiApiFailure` warning covers the far more common REST case: the
    ## transport helpers degrade to NULL on an HTTP 500/timeout rather
    ## than erroring, so an error-only handler silently let the *empty*
    ## live result through and never reached the fixture at all - see
    ## .dtiSignalApiFailure(). Catching that class rather than all
    ## warnings keeps unrelated warnings from triggering a fallback.
    tryCatch(expr,
             error = function(e) useCached(conditionMessage(e)),
             dtiApiFailure = function(w) useCached(conditionMessage(w)))
}
